
biobert:
  model_dir: /home/pengy6/data/sentence_similarity/bert-models/biobert_pubmed
  do_lower_case: False
  max_seq_length: 128
  sts:
    learning_rate: 5e-5
    num_train_epochs: 30
  ner:
    learning_rate: 5e-5
    num_train_epochs: 30
  ddi:
    learning_rate: 5e-5
    num_train_epochs: 10

ncbibert_base:
  model_dir: /home/pengy6/data/sentence_similarity/bert-models/pubmed_uncased_L-12_H-768_A-12
  do_lower_case: True
  max_seq_length: 128
  sts:
    learning_rate: 5e-5
    num_train_epochs: 30
  ner:
    learning_rate: 5e-5
    num_train_epochs: 30
  ddi:
    learning_rate: 5e-5
    num_train_epochs: 10

ncbibert_base_noteevents:
  model_dir: /home/pengy6/data/sentence_similarity/bert-models/pubmed_NOTEEVENTS_uncased_L-12_H-768_A-12
  do_lower_case: True
  max_seq_length: 128
  sts:
    learning_rate: 5e-5
    num_train_epochs: 30
  ner:
    learning_rate: 5e-5
    num_train_epochs: 30
  ddi:
    learning_rate: 5e-5
    num_train_epochs: 10

ncbibert_large:
  model_dir: gs://bucket-tpu-demo/data/bert_pubmed_google_vocab/pubmed_uncased_L-24_H-1024_A-16
  ckpt: 862000
  do_lower_case: True
  max_seq_length: 384
  sts:
    learning_rate: 5e-5
    num_train_epochs: 30
  ner:
    learning_rate: 5e-6
    num_train_epochs: 30


ncbibert_large_noteevents:
  model_dir: gs://bucket-tpu-demo/data/NOTEEVENTS/NOTEEVENTS_uncased_L-24_H-1024_A-16
  ckpt: 383000
  do_lower_case: True
  max_seq_length: 384
  sts:
    learning_rate: 5e-5
    num_train_epochs: 30
  ner:
    learning_rate: 5e-6
    num_train_epochs: 30